"use client";

import { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'hi' | 'gu';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    'app.title': 'VMC CiviSense',
    'login': 'Login',
    'back': 'Back',
    'next': 'Next',
    'save': 'Save',
    'send': 'Send',
    'draft': 'Draft',
    'home.title': 'Vadodara Municipal Corporation',
    'home.subtitle': 'CiviSense - Smart Civic Monitoring',
    'home.login': 'Login to System',
    'feature.geofencing': 'Geo-Fencing',
    'feature.geofencing.desc': 'Auto ward detection using GPS',
    'feature.tracking': 'Issue Tracking',
    'feature.tracking.desc': 'Potholes, garbage, drainage & more',
    'feature.dashboard': 'Role-Based Dashboards',
    'feature.dashboard.desc': 'Field staff to commissioner',
    'feature.mobile': 'Mobile-First PWA',
    'feature.mobile.desc': 'Easy to use, large buttons',
    'feature.offline': 'Offline-First',
    'feature.offline.desc': 'Works without network',
    'feature.ai': 'AI Assistance',
    'feature.ai.desc': 'Smart issue detection',
    'login.title': 'Login to System',
    'login.select.role': 'Select your role to continue',
    'login.signin.as': 'Sign in as',
    'login.username': 'Username or Employee ID',
    'login.password': 'Password',
    'login.remember': 'Remember me',
    'login.forgot': 'Forgot password?',
    'login.signin': 'Sign In',
    'login.change.role': 'Change Role',
    'role.field.worker': 'Field Worker',
    'role.field.worker.desc': 'Report & capture on-ground issues',
    'role.ward.engineer': 'Ward Engineer',
    'role.ward.engineer.desc': 'Monitor & verify ward activities',
    'role.zone.officer': 'Zone Officer',
    'role.zone.officer.desc': 'Oversee multi-ward operations',
    'role.admin': 'Admin',
    'role.admin.desc': 'System-wide management',
    'dashboard.field.worker': 'Field Worker',
    'dashboard.mobile.reporting': 'Mobile Reporting',
    'dashboard.online': 'Online',
    'dashboard.offline': 'Offline',
    'dashboard.saved': 'Saved',
    'dashboard.today': 'Today',
    'dashboard.resolved': 'Resolved',
    'dashboard.report.issue': 'Report Issue',
    'dashboard.quick.photo': 'Quick Photo',
    'dashboard.my.location': 'My Location',
    'dashboard.saved.issues': 'Saved Issues',
    'dashboard.sync.now': 'Sync Now',
    'dashboard.all.synced': 'All Synced',
    'dashboard.will.sync': 'Offline - Will sync when online',
    'issue.report.title': 'Report Issue',
    'issue.select.type': 'Select Issue Type',
    'issue.location.photos': 'Location & Photos',
    'issue.description.submit': 'Description & Submit',
    'issue.get.location': 'Get Location',
    'issue.getting.location': 'Getting Location...',
    'issue.location.captured': 'Location Captured ✓',
    'issue.take.photo': 'Take Photo',
    'issue.description.optional': 'Issue description (optional)',
    'issue.ai.suggestion': 'AI Suggestion',
    'issue.priority': 'Priority',
    'issue.estimated.time': 'Est. Time',
    'issue.location': 'Location',
    'issue.photos': 'Photos',
    'issue.ward': 'Ward',
    'issue.saved.draft': 'Issue saved as draft.',
    'issue.reported.success': 'Issue reported successfully!',
    'issue.fill.required': 'Please fill all required information.',
    'issue.save.error': 'Error saving issue.',
    'issue.location.error': 'Unable to get location. Please enable GPS.',
    'issue.type.pothole': 'Pothole',
    'issue.type.garbage': 'Garbage',
    'issue.type.drainage': 'Drainage',
    'issue.type.streetlight': 'Street Light',
    'issue.type.road': 'Road Damage',
    'issue.type.water': 'Water Issue',
    'issue.type.manhole': 'Open Manhole',
    'issue.type.cattle': 'Stray Cattle',
    'network.no.connection': 'No internet connection.',
    'network.syncing': 'Syncing...',
    'network.sync.complete': 'All data synced!',
    'network.sync.error': 'Sync error.',
    'photo.captured': 'Photo captured! Report it later.',
    'photo.location.not.available': 'Location not available'
  },
  
  hi: {
    'app.title': 'वीएमसी सिविसेंस',
    'login': 'लॉगिन',
    'back': 'पीछे',
    'next': 'आगे',
    'save': 'सेव',
    'send': 'भेजें',
    'draft': 'ड्राफ्ट',
    'home.title': 'वडोदरा नगर निगम',
    'home.subtitle': 'सिविसेंस - स्मार्ट सिविक मॉनिटरिंग',
    'home.login': 'सिस्टम में लॉगिन करें',
    'feature.geofencing': 'जियो-फेंसिंग',
    'feature.geofencing.desc': 'GPS से अपने आप वार्ड की पहचान',
    'feature.tracking': 'समस्या ट्रैकिंग',
    'feature.tracking.desc': 'गड्डे, कचरा, नाली और अन्य',
    'feature.dashboard': 'रोल-बेस्ड डैशबोर्ड',
    'feature.dashboard.desc': 'फील्ड स्टाफ से कमिश्नर तक',
    'feature.mobile': 'मोबाइल-फर्स्ट PWA',
    'feature.mobile.desc': 'आसान उपयोग, बड़े बटन',
    'feature.offline': 'ऑफलाइन-फर्स्ट',
    'feature.offline.desc': 'नेटवर्क के बिना भी काम करता है',
    'feature.ai': 'AI सहायता',
    'feature.ai.desc': 'स्मार्ट समस्या पहचान',
    'login.title': 'सिस्टम में लॉगिन करें',
    'login.select.role': 'जारी रखने के लिए अपनी भूमिका चुनें',
    'login.signin.as': 'के रूप में साइन इन करें',
    'login.username': 'यूजरनेम या कर्मचारी आईडी',
    'login.password': 'पासवर्ड',
    'login.remember': 'मुझे याद रखें',
    'login.forgot': 'पासवर्ड भूल गए?',
    'login.signin': 'साइन इन',
    'login.change.role': 'भूमिका बदलें',
    'role.field.worker': 'फील्ड वर्कर',
    'role.field.worker.desc': 'जमीनी समस्याओं की रिपोर्ट और कैप्चर',
    'role.ward.engineer': 'वार्ड इंजीनियर',
    'role.ward.engineer.desc': 'वार्ड गतिविधियों की निगरानी और सत्यापन',
    'role.zone.officer': 'जोन अधिकारी',
    'role.zone.officer.desc': 'बहु-वार्ड संचालन की देखरेख',
    'role.admin': 'एडमिन',
    'role.admin.desc': 'सिस्टम-व्यापी प्रबंधन',
    'dashboard.field.worker': 'फील्ड वर्कर',
    'dashboard.mobile.reporting': 'मोबाइल रिपोर्टिंग',
    'dashboard.online': 'ऑनलाइन',
    'dashboard.offline': 'ऑफलाइन',
    'dashboard.saved': 'सेव्ड',
    'dashboard.today': 'आज',
    'dashboard.resolved': 'हल',
    'dashboard.report.issue': 'समस्या रिपोर्ट करें',
    'dashboard.quick.photo': 'त्वरित फोटो',
    'dashboard.my.location': 'मेरा स्थान',
    'dashboard.saved.issues': 'सेव्ड इश्यूज',
    'dashboard.sync.now': 'सिंक करें',
    'dashboard.all.synced': 'सभी सिंक हो गया',
    'dashboard.will.sync': 'ऑफलाइन - ऑनलाइन होने पर सिंक होगा',
    'issue.report.title': 'समस्या रिपोर्ट करें',
    'issue.select.type': 'समस्या का प्रकार चुनें',
    'issue.location.photos': 'स्थान और फोटो',
    'issue.description.submit': 'विवरण और सबमिट',
    'issue.get.location': 'स्थान प्राप्त करें',
    'issue.getting.location': 'स्थान प्राप्त कर रहे हैं...',
    'issue.location.captured': 'स्थान मिल गया ✓',
    'issue.take.photo': 'फोटो लें',
    'issue.description.optional': 'समस्या का विवरण (वैकल्पिक)',
    'issue.ai.suggestion': 'AI सुझाव',
    'issue.priority': 'प्राथमिकता',
    'issue.estimated.time': 'अनुमानित समय',
    'issue.location': 'स्थान',
    'issue.photos': 'फोटो',
    'issue.ward': 'वार्ड',
    'issue.saved.draft': 'मुद्दा ड्राफ्ट में सेव हो गया।',
    'issue.reported.success': 'मुद्दा रिपोर्ट हो गया!',
    'issue.fill.required': 'कृपया सभी आवश्यक जानकारी भरें।',
    'issue.save.error': 'सेव करने में त्रुटि।',
    'issue.location.error': 'स्थान प्राप्त नहीं हो सका। कृपया GPS चालू करें।',
    'issue.type.pothole': 'गड्डा',
    'issue.type.garbage': 'कचरा',
    'issue.type.drainage': 'नाली',
    'issue.type.streetlight': 'बत्ती',
    'issue.type.road': 'सड़क',
    'issue.type.water': 'पानी',
    'issue.type.manhole': 'खुला मैनहोल',
    'issue.type.cattle': 'आवारा पशु',
    'network.no.connection': 'इंटरनेट कनेक्शन नहीं है।',
    'network.syncing': 'सिंक हो रहा है...',
    'network.sync.complete': 'सभी डेटा सिंक हो गया!',
    'network.sync.error': 'सिंक में त्रुटि।',
    'photo.captured': 'फोटो कैप्चर हो गई! बाद में रिपोर्ट करें।',
    'photo.location.not.available': 'स्थान उपलब्ध नहीं है'
  },
  
  gu: {
    'app.title': 'વીએમસી સિવિસેન્સ',
    'login': 'લોગિન',
    'back': 'પાછળ',
    'next': 'આગળ',
    'save': 'સેવ',
    'send': 'મોકલો',
    'draft': 'ડ્રાફ્ટ',
    'home.title': 'વડોદરા મહાનગરપાલિકા',
    'home.subtitle': 'સિવિસેન્સ - સ્માર્ટ સિવિક મોનિટરિંગ',
    'home.login': 'સિસ્ટમમાં લોગિન કરો',
    'feature.geofencing': 'જીઓ-ફેન્સિંગ',
    'feature.geofencing.desc': 'GPS થી આપોઆપ વોર્ડની ઓળખ',
    'feature.tracking': 'સમસ્યા ટ્રેકિંગ',
    'feature.tracking.desc': 'ખાડા, કચરો, ગટર અને અન્ય',
    'feature.dashboard': 'રોલ-બેસ્ડ ડેશબોર્ડ',
    'feature.dashboard.desc': 'ફીલ્ડ સ્ટાફથી કમિશનર સુધી',
    'feature.mobile': 'મોબાઇલ-ફર્સ્ટ PWA',
    'feature.mobile.desc': 'સરળ ઉપયોગ, મોટા બટન',
    'feature.offline': 'ઓફલાઇન-ફર્સ્ટ',
    'feature.offline.desc': 'નેટવર્ક વિના પણ કામ કરે છે',
    'feature.ai': 'AI સહાય',
    'feature.ai.desc': 'સ્માર્ટ સમસ્યા ઓળખ',
    'login.title': 'સિસ્ટમમાં લોગિન કરો',
    'login.select.role': 'ચાલુ રાખવા માટે તમારી ભૂમિકા પસંદ કરો',
    'login.signin.as': 'તરીકે સાઇન ઇન કરો',
    'login.username': 'યુઝરનેમ અથવા કર્મચારી આઇડી',
    'login.password': 'પાસવર્ડ',
    'login.remember': 'મને યાદ રાખો',
    'login.forgot': 'પાસવર્ડ ભૂલી ગયા?',
    'login.signin': 'સાઇન ઇન',
    'login.change.role': 'ભૂમિકા બદલો',
    'role.field.worker': 'ફીલ્ડ વર્કર',
    'role.field.worker.desc': 'જમીની સમસ્યાઓની રિપોર્ટ અને કેપ્ચર',
    'role.ward.engineer': 'વોર્ડ એન્જિનિયર',
    'role.ward.engineer.desc': 'વોર્ડ પ્રવૃત્તિઓનું નિરીક્ષણ અને ચકાસણી',
    'role.zone.officer': 'ઝોન અધિકારી',
    'role.zone.officer.desc': 'બહુ-વોર્ડ સંચાલનની દેખરેખ',
    'role.admin': 'એડમિન',
    'role.admin.desc': 'સિસ્ટમ-વ્યાપી વ્યવસ્થાપન',
    'dashboard.field.worker': 'ફીલ્ડ વર્કર',
    'dashboard.mobile.reporting': 'મોબાઇલ રિપોર્ટિંગ',
    'dashboard.online': 'ઓનલાઇન',
    'dashboard.offline': 'ઓફલાઇન',
    'dashboard.saved': 'સેવ્ડ',
    'dashboard.today': 'આજે',
    'dashboard.resolved': 'હલ',
    'dashboard.report.issue': 'સમસ્યા રિપોર્ટ કરો',
    'dashboard.quick.photo': 'ઝડપી ફોટો',
    'dashboard.my.location': 'મારું સ્થાન',
    'dashboard.saved.issues': 'સેવ્ડ ઇશ્યૂઝ',
    'dashboard.sync.now': 'સિંક કરો',
    'dashboard.all.synced': 'બધું સિંક થઈ ગયું',
    'dashboard.will.sync': 'ઓફલાઇન - ઓનલાઇન થવા પર સિંક થશે',
    'issue.report.title': 'સમસ્યા રિપોર્ટ કરો',
    'issue.select.type': 'સમસ્યાનો પ્રકાર પસંદ કરો',
    'issue.location.photos': 'સ્થાન અને ફોટો',
    'issue.description.submit': 'વર્ણન અને સબમિટ',
    'issue.get.location': 'સ્થાન મેળવો',
    'issue.getting.location': 'સ્થાન મેળવી રહ્યા છીએ...',
    'issue.location.captured': 'સ્થાન મળી ગયું ✓',
    'issue.take.photo': 'ફોટો લો',
    'issue.description.optional': 'સમસ્યાનું વર્ણન (વૈકલ્પિક)',
    'issue.ai.suggestion': 'AI સૂચન',
    'issue.priority': 'પ્રાથમિકતા',
    'issue.estimated.time': 'અનુમાનિત સમય',
    'issue.location': 'સ્થાન',
    'issue.photos': 'ફોટો',
    'issue.ward': 'વોર્ડ',
    'issue.saved.draft': 'મુદ્દો ડ્રાફ્ટમાં સેવ થઈ ગયો.',
    'issue.reported.success': 'મુદ્દો રિપોર્ટ થઈ ગયો!',
    'issue.fill.required': 'કૃપા કરીને બધી જરૂરી માહિતી ભરો.',
    'issue.save.error': 'સેવ કરવામાં ભૂલ.',
    'issue.location.error': 'સ્થાન મેળવી શકાયું નથી. કૃપા કરીને GPS ચાલુ કરો.',
    'issue.type.pothole': 'ખાડો',
    'issue.type.garbage': 'કચરો',
    'issue.type.drainage': 'ગટર',
    'issue.type.streetlight': 'સ્ટ્રીટ લાઇટ',
    'issue.type.road': 'રસ્તો',
    'issue.type.water': 'પાણી',
    'issue.type.manhole': 'ખુલ્લું મેનહોલ',
    'issue.type.cattle': 'આવારા પશુઓ',
    'network.no.connection': 'ઇન્ટરનેટ કનેક્શન નથી.',
    'network.syncing': 'સિંક થઈ રહ્યું છે...',
    'network.sync.complete': 'બધો ડેટા સિંક થઈ ગયો!',
    'network.sync.error': 'સિંકમાં ભૂલ.',
    'photo.captured': 'ફોટો કેપ્ચર થઈ ગયો! પછીથી રિપોર્ટ કરો.',
    'photo.location.not.available': 'સ્થાન ઉપલબ્ધ નથી'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    const savedLang = localStorage.getItem('vmc-language') as Language;
    if (savedLang && ['en', 'hi', 'gu'].includes(savedLang)) {
      setLanguage(savedLang);
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('vmc-language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}