"use client";

import { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'hi' | 'gu';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  getLanguageCode: () => string;
}

const LANGUAGE_CODES: Record<Language, string> = {
  en: 'en-US',
  hi: 'hi-IN',
  gu: 'gu-IN',
};

const translations = {
  en: {
    'app.title': 'VMC CiviSense',
    'login': 'Login',
    'back': 'Back',
    'next': 'Next',
    'save': 'Save',
    'send': 'Send',
    'draft': 'Draft',
    'home.title': 'Vadodara Municipal Corporation',
    'home.subtitle': 'CiviSense - Smart Civic Monitoring',
    'home.login': 'Login to System',
    'feature.geofencing': 'Geo-Fencing',
    'feature.geofencing.desc': 'Auto ward detection using GPS',
    'feature.tracking': 'Issue Tracking',
    'feature.tracking.desc': 'Potholes, garbage, drainage & more',
    'feature.dashboard': 'Role-Based Dashboards',
    'feature.dashboard.desc': 'Field staff to commissioner',
    'feature.mobile': 'Mobile-First PWA',
    'feature.mobile.desc': 'Easy to use, large buttons',
    'feature.offline': 'Offline-First',
    'feature.offline.desc': 'Works without network',
    'feature.ai': 'AI Assistance',
    'feature.ai.desc': 'Smart issue detection',
    'login.title': 'Login to System',
    'login.select.role': 'Select your role to continue',
    'login.signin.as': 'Sign in as',
    'login.username': 'Username or Employee ID',
    'login.password': 'Password',
    'login.remember': 'Remember me',
    'login.forgot': 'Forgot password?',
    'login.signin': 'Sign In',
    'login.change.role': 'Change Role',
    'role.field.worker': 'Field Worker',
    'role.field.worker.desc': 'Report & capture on-ground issues',
    'role.ward.engineer': 'Ward Engineer',
    'role.ward.engineer.desc': 'Monitor & verify ward activities',
    'role.zone.officer': 'Zone Officer',
    'role.zone.officer.desc': 'Oversee multi-ward operations',
    'role.admin': 'Admin',
    'role.admin.desc': 'System-wide management',
    'dashboard.field.worker': 'Field Worker',
    'dashboard.mobile.reporting': 'Mobile Reporting',
    'dashboard.online': 'Online',
    'dashboard.offline': 'Offline',
    'dashboard.saved': 'Saved',
    'dashboard.today': 'Today',
    'dashboard.resolved': 'Resolved',
    'dashboard.report.issue': 'Report Issue',
    'dashboard.quick.photo': 'Quick Photo',
    'dashboard.my.location': 'My Location',
    'dashboard.saved.issues': 'Saved Issues',
    'dashboard.sync.now': 'Sync Now',
    'dashboard.all.synced': 'All Synced',
    'dashboard.will.sync': 'Offline - Will sync when online',
    'issue.report.title': 'Report Issue',
    'issue.select.type': 'Select Issue Type',
    'issue.location.photos': 'Location & Photos',
    'issue.description.submit': 'Description & Submit',
    'issue.get.location': 'Get Location',
    'issue.getting.location': 'Getting Location...',
    'issue.location.captured': 'Location Captured ✓',
    'issue.take.photo': 'Take Photo',
    'issue.description.optional': 'Issue description (optional)',
    'issue.ai.suggestion': 'AI Suggestion',
    'issue.priority': 'Priority',
    'issue.estimated.time': 'Est. Time',
    'issue.location': 'Location',
    'issue.photos': 'Photos',
    'issue.ward': 'Ward',
    'issue.saved.draft': 'Issue saved as draft.',
    'issue.reported.success': 'Issue reported successfully!',
    'issue.fill.required': 'Please fill all required information.',
    'issue.save.error': 'Error saving issue.',
    'issue.location.error': 'Unable to get location. Please enable GPS.',
    'issue.type.pothole': 'Pothole',
    'issue.type.garbage': 'Garbage',
    'issue.type.drainage': 'Drainage',
    'issue.type.streetlight': 'Street Light',
    'issue.type.road': 'Road Damage',
    'issue.type.water': 'Water Issue',
    'issue.type.manhole': 'Open Manhole',
    'issue.type.cattle': 'Stray Cattle',
    'network.no.connection': 'No internet connection.',
    'network.syncing': 'Syncing...',
    'network.sync.complete': 'All data synced!',
    'network.sync.error': 'Sync error.',
    'photo.captured': 'Photo captured! Report it later.',
    'photo.location.not.available': 'Location not available',
    'home.description': 'AI-Based Geo-Fenced Civic Issue Monitoring System for field staff',
    'home.use.cases.title': 'Key Use Cases',
    'home.use.case.pothole': 'Detect potholes after monsoon inspections',
    'home.use.case.garbage': 'Identify garbage accumulation hotspots',
    'home.use.case.cattle': 'Report stray cattle on roads',
    'home.use.case.manhole': 'Flag open manholes or damaged roads',
    'home.use.case.resolution': 'Enable faster ward-wise issue resolution',
    'home.use.case.accountability': 'Improve accountability with resolution proof',
    'login.role.description': 'Field Worker, Ward Engineer, Zone Officer or Admin',
    'about.vadodara.title': 'About Our Vadodara',
    'about.vadodara.subtitle': 'Sanskari Nagari',
    'about.vadodara.para1': 'Vadodara, also known as Baroda, is one of Gujarat\'s most vibrant cities — a blend of rich heritage, cultural diversity, and rapid urban development. Situated on the banks of the Vishwamitri River, it is renowned for its grand palaces, art museums, and educational institutions. Once the seat of the Gaekwad dynasty, Vadodara continues to reflect regal charm through its architecture and traditions.',
    'about.vadodara.para2': 'Today, Vadodara stands as a fast-growing smart city, embracing digital governance, infrastructure modernization, and sustainable growth. With a strong industrial base, particularly in petrochemicals, engineering, and IT, the city also thrives as a hub for innovation and civic progress. Vadodara is not just a city — it\'s a progressive community where culture meets technology.',
    'city.highlights.title': 'City Highlights',
    'city.highlight.smart.city': 'Smart City Initiatives',
    'city.highlight.smart.city.desc': 'Vadodara is part of the Smart Cities Mission, implementing digital infrastructure, intelligent traffic systems, and e-governance services to enhance urban living.',
    'city.highlight.cultural': 'Cultural Heritage',
    'city.highlight.cultural.desc': 'Home to landmarks like Lukshmi Vilas Palace and Sayaji Garden, Vadodara celebrates its royal legacy and vibrant festivals like Navratri with grandeur.',
    'city.highlight.citizen': 'Citizen Services',
    'city.highlight.citizen.desc': 'From online bill payments to complaint redressal, VMC provides easy access to essential municipal services through its digital platforms.',
    'city.highlight.sustainable': 'Sustainable Development',
    'city.highlight.sustainable.desc': 'Focused on green spaces, water management, and clean energy projects, Vadodara is actively working towards an eco-friendly urban future.',
    'city.highlight.industrial': 'Industrial & Educational Hub',
    'city.highlight.industrial.desc': 'With key industries and prestigious institutions like The Maharaja Sayajirao University, Vadodara is a center for economic and academic excellence.',
    'header.tagline': 'Vadodara Municipal Corporation',
    'header.accessibility': 'Accessibility Options',
    'header.nav.field.worker': 'Field Worker Dashboard',
    'header.nav.ward.engineer': 'Ward Engineer Dashboard',
    'header.nav.zone.officer': 'Zone Officer Dashboard',
    'header.nav.admin': 'Admin Dashboard',
    'footer.description.line1': 'AI-Based Geo-Fenced Civic Issue Monitoring System for Vadodara Municipal Corporation',
    'footer.description.line2': 'Empowering field staff with offline-first technology',
    'footer.contact.title': 'Contact VMC',
    'footer.quick.links.title': 'Quick Links',
    'footer.portal.field.worker': 'Field Worker Portal',
    'footer.portal.ward.engineer': 'Ward Engineer Portal',
    'footer.portal.zone.officer': 'Zone Officer Portal',
    'footer.portal.admin': 'Admin Portal',
    'footer.copyright': '© 2026 Vadodara Municipal Corporation. All rights reserved.',
    'footer.made.for': 'Made for VMC Field Staff',
    'footer.offline.pwa': 'Offline-First PWA',
    'footer.gps.enabled': 'GPS Enabled',
    'compliance.title': 'Government Compliance',
    'compliance.description': 'VMC CiviSense adheres to all government standards and regulations',
    'compliance.data.security': 'Data Security',
    'compliance.data.security.desc': 'End-to-end encryption, secure data storage, and regular security audits',
    'compliance.data.security.std1': 'ISO 27001',
    'compliance.data.security.std2': 'GDPR Compliant',
    'compliance.data.security.std3': 'Government Grade Security',
    'compliance.accessibility': 'Accessibility',
    'compliance.accessibility.desc': 'WCAG 2.1 AA compliant with screen reader support and keyboard navigation',
    'compliance.accessibility.std1': 'WCAG 2.1 AA',
    'compliance.accessibility.std2': 'Section 508',
    'compliance.accessibility.std3': 'Multi-language Support',
    'compliance.transparency': 'Transparency',
    'compliance.transparency.desc': 'Open data policies, audit trails, and public accountability measures',
    'compliance.transparency.std1': 'RTI Compliant',
    'compliance.transparency.std2': 'Audit Trails',
    'compliance.transparency.std3': 'Public Data Access',
    'compliance.privacy': 'Privacy Protection',
    'compliance.privacy.desc': 'Citizen data protection with consent management and privacy controls',
    'compliance.privacy.std1': 'Privacy by Design',
    'compliance.privacy.std2': 'Consent Management',
    'compliance.privacy.std3': 'Data Minimization',
    'compliance.digital.india': 'Digital India',
    'compliance.digital.india.desc': 'Aligned with Digital India initiatives and e-governance standards',
    'compliance.digital.india.std1': 'Digital India',
    'compliance.digital.india.std2': 'e-Governance',
    'compliance.digital.india.std3': 'API Standards',
    'compliance.cyber.security': 'Cyber Security',
    'compliance.cyber.security.desc': 'Regular penetration testing, vulnerability assessments, and security monitoring',
    'compliance.cyber.security.std1': 'CERT-In Guidelines',
    'compliance.cyber.security.std2': 'Cyber Security Framework',
    'compliance.cyber.security.std3': '24/7 Monitoring',
    'compliance.certification.title': 'Certification & Compliance Status',
    'compliance.cert.security.audit': 'Security Audit',
    'compliance.cert.security.audit.status': '✓ Passed',
    'compliance.cert.accessibility.test': 'Accessibility Test',
    'compliance.cert.accessibility.test.status': '✓ AA Compliant',
    'compliance.cert.data.protection': 'Data Protection',
    'compliance.cert.data.protection.status': '✓ Certified',
    'compliance.cert.performance': 'Performance',
    'compliance.cert.performance.status': '✓ Optimized',
    'forgot.password.title': 'Reset Password',
    'forgot.password.description': 'Enter your email to receive an OTP',
    'forgot.password.email.label': 'Email Address',
    'forgot.password.email.placeholder': 'engineer@vmc.gov.in',
    'forgot.password.send.otp': 'Send OTP',
    'forgot.password.sending': 'Sending...',
    'forgot.password.back.to.login': 'Back to Login',
    'forgot.password.otp.title': 'Enter OTP',
    'forgot.password.otp.description': 'Enter the OTP sent to your email',
    'forgot.password.otp.sent': "We've sent a 6-digit code to",
    'forgot.password.verify.otp': 'Verify OTP',
    'forgot.password.verifying': 'Verifying...',
    'forgot.password.resend.otp': 'Resend OTP',
    'forgot.password.change.email': 'Change Email',
    'forgot.password.new.password': 'New Password',
    'forgot.password.new.password.description': 'Create a new secure password',
    'forgot.password.new.password.placeholder': 'Enter new password',
    'forgot.password.confirm.password': 'Confirm Password',
    'forgot.password.confirm.password.placeholder': 'Re-enter new password',
    'forgot.password.show.password': 'Show password',
    'forgot.password.requirements': 'Password must contain:',
    'forgot.password.requirement.length': 'At least 8 characters',
    'forgot.password.requirement.mix': 'Mix of letters and numbers',
    'forgot.password.reset.button': 'Reset Password',
    'forgot.password.resetting': 'Resetting...',
    'forgot.password.success': 'Password Reset Successful!',
    'forgot.password.success.description': 'Your password has been reset successfully',
    'forgot.password.success.message': 'Your password has been reset successfully. You can now log in with your new password.',
    'forgot.password.go.to.login': 'Go to Login',
    'forgot.password.step.email': 'Email',
    'forgot.password.step.otp': 'OTP',
    'forgot.password.step.password': 'Password',
    'forgot.password.error.invalid.email': 'Please enter a valid email address',
    'forgot.password.error.invalid.otp': 'Please enter a valid 6-digit OTP',
    'forgot.password.error.password.mismatch': 'Passwords do not match',
    'forgot.password.error.password.weak': 'Password must be at least 8 characters'
  },
  
  hi: {
    'app.title': 'वीएमसी सिविसेंस',
    'login': 'लॉगिन',
    'back': 'पीछे',
    'next': 'आगे',
    'save': 'सेव',
    'send': 'भेजें',
    'draft': 'ड्राफ्ट',
    'home.title': 'वडोदरा नगर निगम',
    'home.subtitle': 'सिविसेंस - स्मार्ट सिविक मॉनिटरिंग',
    'home.login': 'सिस्टम में लॉगिन करें',
    'feature.geofencing': 'जियो-फेंसिंग',
    'feature.geofencing.desc': 'GPS से अपने आप वार्ड की पहचान',
    'feature.tracking': 'समस्या ट्रैकिंग',
    'feature.tracking.desc': 'गड्डे, कचरा, नाली और अन्य',
    'feature.dashboard': 'रोल-बेस्ड डैशबोर्ड',
    'feature.dashboard.desc': 'फील्ड स्टाफ से कमिश्नर तक',
    'feature.mobile': 'मोबाइल-फर्स्ट PWA',
    'feature.mobile.desc': 'आसान उपयोग, बड़े बटन',
    'feature.offline': 'ऑफलाइन-फर्स्ट',
    'feature.offline.desc': 'नेटवर्क के बिना भी काम करता है',
    'feature.ai': 'AI सहायता',
    'feature.ai.desc': 'स्मार्ट समस्या पहचान',
    'login.title': 'सिस्टम में लॉगिन करें',
    'login.select.role': 'जारी रखने के लिए अपनी भूमिका चुनें',
    'login.signin.as': 'के रूप में साइन इन करें',
    'login.username': 'यूजरनेम या कर्मचारी आईडी',
    'login.password': 'पासवर्ड',
    'login.remember': 'मुझे याद रखें',
    'login.forgot': 'पासवर्ड भूल गए?',
    'login.signin': 'साइन इन',
    'login.change.role': 'भूमिका बदलें',
    'role.field.worker': 'फील्ड वर्कर',
    'role.field.worker.desc': 'जमीनी समस्याओं की रिपोर्ट और कैप्चर',
    'role.ward.engineer': 'वार्ड इंजीनियर',
    'role.ward.engineer.desc': 'वार्ड गतिविधियों की निगरानी और सत्यापन',
    'role.zone.officer': 'जोन अधिकारी',
    'role.zone.officer.desc': 'बहु-वार्ड संचालन की देखरेख',
    'role.admin': 'एडमिन',
    'role.admin.desc': 'सिस्टम-व्यापी प्रबंधन',
    'dashboard.field.worker': 'फील्ड वर्कर',
    'dashboard.mobile.reporting': 'मोबाइल रिपोर्टिंग',
    'dashboard.online': 'ऑनलाइन',
    'dashboard.offline': 'ऑफलाइन',
    'dashboard.saved': 'सेव्ड',
    'dashboard.today': 'आज',
    'dashboard.resolved': 'हल',
    'dashboard.report.issue': 'समस्या रिपोर्ट करें',
    'dashboard.quick.photo': 'त्वरित फोटो',
    'dashboard.my.location': 'मेरा स्थान',
    'dashboard.saved.issues': 'सेव्ड इश्यूज',
    'dashboard.sync.now': 'सिंक करें',
    'dashboard.all.synced': 'सभी सिंक हो गया',
    'dashboard.will.sync': 'ऑफलाइन - ऑनलाइन होने पर सिंक होगा',
    'issue.report.title': 'समस्या रिपोर्ट करें',
    'issue.select.type': 'समस्या का प्रकार चुनें',
    'issue.location.photos': 'स्थान और फोटो',
    'issue.description.submit': 'विवरण और सबमिट',
    'issue.get.location': 'स्थान प्राप्त करें',
    'issue.getting.location': 'स्थान प्राप्त कर रहे हैं...',
    'issue.location.captured': 'स्थान मिल गया ✓',
    'issue.take.photo': 'फोटो लें',
    'issue.description.optional': 'समस्या का विवरण (वैकल्पिक)',
    'issue.ai.suggestion': 'AI सुझाव',
    'issue.priority': 'प्राथमिकता',
    'issue.estimated.time': 'अनुमानित समय',
    'issue.location': 'स्थान',
    'issue.photos': 'फोटो',
    'issue.ward': 'वार्ड',
    'issue.saved.draft': 'मुद्दा ड्राफ्ट में सेव हो गया।',
    'issue.reported.success': 'मुद्दा रिपोर्ट हो गया!',
    'issue.fill.required': 'कृपया सभी आवश्यक जानकारी भरें।',
    'issue.save.error': 'सेव करने में त्रुटि।',
    'issue.location.error': 'स्थान प्राप्त नहीं हो सका। कृपया GPS चालू करें।',
    'issue.type.pothole': 'गड्डा',
    'issue.type.garbage': 'कचरा',
    'issue.type.drainage': 'नाली',
    'issue.type.streetlight': 'बत्ती',
    'issue.type.road': 'सड़क',
    'issue.type.water': 'पानी',
    'issue.type.manhole': 'खुला मैनहोल',
    'issue.type.cattle': 'आवारा पशु',
    'network.no.connection': 'इंटरनेट कनेक्शन नहीं है।',
    'network.syncing': 'सिंक हो रहा है...',
    'network.sync.complete': 'सभी डेटा सिंक हो गया!',
    'network.sync.error': 'सिंक में त्रुटि।',
    'photo.captured': 'फोटो कैप्चर हो गई! बाद में रिपोर्ट करें।',
    'photo.location.not.available': 'स्थान उपलब्ध नहीं है',
    'home.description': 'फील्ड स्टाफ के लिए AI-आधारित जियो-फेंस्ड सिविक इश्यू मॉनिटरिंग सिस्टम',
    'home.use.cases.title': 'मुख्य उपयोग के मामले',
    'home.use.case.pothole': 'मानसून निरीक्षण के बाद गड्ढों का पता लगाएं',
    'home.use.case.garbage': 'कचरा जमा होने वाले हॉटस्पॉट की पहचान करें',
    'home.use.case.cattle': 'सड़कों पर आवारा पशुओं की रिपोर्ट करें',
    'home.use.case.manhole': 'खुले मैनहोल या क्षतिग्रस्त सड़कों को चिह्नित करें',
    'home.use.case.resolution': 'वार्ड-वार समस्या समाधान को तेज़ करें',
    'home.use.case.accountability': 'समाधान प्रमाण के साथ जवाबदेही में सुधार करें',
    'login.role.description': 'फील्ड वर्कर, वार्ड इंजीनियर, जोन अधिकारी या एडमिन',
    'about.vadodara.title': 'हमारे वडोदरा के बारे में',
    'about.vadodara.subtitle': 'संस्कारी नगरी',
    'about.vadodara.para1': 'वडोदरा, जिसे बड़ौदा के नाम से भी जाना जाता है, गुजरात के सबसे जीवंत शहरों में से एक है — जो समृद्ध विरासत, सांस्कृतिक विविधता और तीव्र शहरी विकास का मिश्रण है। विश्वामित्री नदी के तट पर स्थित, यह अपने भव्य महलों, कला संग्रहालयों और शैक्षणिक संस्थानों के लिए प्रसिद्ध है। एक समय गायकवाड़ राजवंश की राजधानी रहा वडोदरा आज भी अपनी वास्तुकला और परंपराओं के माध्यम से शाही आकर्षण को दर्शाता है।',
    'about.vadodara.para2': 'आज, वडोदरा एक तेजी से बढ़ते स्मार्ट शहर के रूप में खड़ा है, जो डिजिटल शासन, बुनियादी ढांचे के आधुनिकीकरण और सतत विकास को अपना रहा है। पेट्रोकेमिकल्स, इंजीनियरिंग और आईटी में मजबूत औद्योगिक आधार के साथ, यह शहर नवाचार और नागरिक प्रगति के केंद्र के रूप में भी फल-फूल रहा है। वडोदरा सिर्फ एक शहर नहीं है — यह एक प्रगतिशील समुदाय है जहां संस्कृति प्रौद्योगिकी से मिलती है।',
    'city.highlights.title': 'शहर की मुख्य बातें',
    'city.highlight.smart.city': 'स्मार्ट सिटी पहल',
    'city.highlight.smart.city.desc': 'वडोदरा स्मार्ट सिटीज मिशन का हिस्सा है, जो शहरी जीवन को बेहतर बनाने के लिए डिजिटल बुनियादी ढांचा, बुद्धिमान यातायात प्रणाली और ई-गवर्नेंस सेवाओं को लागू कर रहा है।',
    'city.highlight.cultural': 'सांस्कृतिक विरासत',
    'city.highlight.cultural.desc': 'लक्ष्मी विलास पैलेस और सयाजी गार्डन जैसे स्थलों का घर, वडोदरा अपनी शाही विरासत और नवरात्रि जैसे जीवंत त्योहारों को भव्यता से मनाता है।',
    'city.highlight.citizen': 'नागरिक सेवाएं',
    'city.highlight.citizen.desc': 'ऑनलाइन बिल भुगतान से लेकर शिकायत निवारण तक, वीएमसी अपने डिजिटल प्लेटफार्मों के माध्यम से आवश्यक नगरपालिका सेवाओं तक आसान पहुंच प्रदान करता है।',
    'city.highlight.sustainable': 'सतत विकास',
    'city.highlight.sustainable.desc': 'हरित स्थानों, जल प्रबंधन और स्वच्छ ऊर्जा परियोजनाओं पर केंद्रित, वडोदरा पर्यावरण के अनुकूल शहरी भविष्य की दिशा में सक्रिय रूप से काम कर रहा है।',
    'city.highlight.industrial': 'औद्योगिक और शैक्षणिक केंद्र',
    'city.highlight.industrial.desc': 'महाराजा सयाजीराव विश्वविद्यालय जैसे प्रमुख उद्योगों और प्रतिष्ठित संस्थानों के साथ, वडोदरा आर्थिक और शैक्षणिक उत्कृष्टता का केंद्र है।',
    'header.tagline': 'वडोदरा नगर निगम',
    'header.accessibility': 'एक्सेसिबिलिटी विकल्प',
    'header.nav.field.worker': 'फील्ड वर्कर डैशबोर्ड',
    'header.nav.ward.engineer': 'वार्ड इंजीनियर डैशबोर्ड',
    'header.nav.zone.officer': 'जोन अधिकारी डैशबोर्ड',
    'header.nav.admin': 'एडमिन डैशबोर्ड',
    'footer.description.line1': 'वडोदरा नगर निगम के लिए AI-आधारित जियो-फेंस्ड सिविक इश्यू मॉनिटरिंग सिस्टम',
    'footer.description.line2': 'ऑफलाइन-फर्स्ट तकनीक के साथ फील्ड स्टाफ को सशक्त बनाना',
    'footer.contact.title': 'VMC से संपर्क करें',
    'footer.quick.links.title': 'त्वरित लिंक',
    'footer.portal.field.worker': 'फील्ड वर्कर पोर्टल',
    'footer.portal.ward.engineer': 'वार्ड इंजीनियर पोर्टल',
    'footer.portal.zone.officer': 'जोन अधिकारी पोर्टल',
    'footer.portal.admin': 'एडमिन पोर्टल',
    'footer.copyright': '© 2026 वडोदरा नगर निगम। सर्वाधिकार सुरक्षित।',
    'footer.made.for': 'VMC फील्ड स्टाफ के लिए बनाया गया',
    'footer.offline.pwa': 'ऑफलाइन-फर्स्ट PWA',
    'footer.gps.enabled': 'GPS सक्षम',
    'compliance.title': 'सरकारी अनुपालन',
    'compliance.description': 'VMC सिविसेंस सभी सरकारी मानकों और नियमों का पालन करता है',
    'compliance.data.security': 'डेटा सुरक्षा',
    'compliance.data.security.desc': 'एंड-टू-एंड एन्क्रिप्शन, सुरक्षित डेटा स्टोरेज और नियमित सुरक्षा ऑडिट',
    'compliance.data.security.std1': 'ISO 27001',
    'compliance.data.security.std2': 'GDPR अनुपालक',
    'compliance.data.security.std3': 'सरकारी ग्रेड सुरक्षा',
    'compliance.accessibility': 'एक्सेसिबिलिटी',
    'compliance.accessibility.desc': 'स्क्रीन रीडर सपोर्ट और कीबोर्ड नेविगेशन के साथ WCAG 2.1 AA अनुपालक',
    'compliance.accessibility.std1': 'WCAG 2.1 AA',
    'compliance.accessibility.std2': 'सेक्शन 508',
    'compliance.accessibility.std3': 'बहुभाषी समर्थन',
    'compliance.transparency': 'पारदर्शिता',
    'compliance.transparency.desc': 'ओपन डेटा नीतियां, ऑडिट ट्रेल्स और सार्वजनिक जवाबदेही उपाय',
    'compliance.transparency.std1': 'RTI अनुपालक',
    'compliance.transparency.std2': 'ऑडिट ट्रेल्स',
    'compliance.transparency.std3': 'सार्वजनिक डेटा पहुंच',
    'compliance.privacy': 'गोपनीयता सुरक्षा',
    'compliance.privacy.desc': 'सहमति प्रबंधन और गोपनीयता नियंत्रण के साथ नागरिक डेटा संरक्षण',
    'compliance.privacy.std1': 'प्राइवेसी बाय डिजाइन',
    'compliance.privacy.std2': 'सहमति प्रबंधन',
    'compliance.privacy.std3': 'डेटा न्यूनीकरण',
    'compliance.digital.india': 'डिजिटल इंडिया',
    'compliance.digital.india.desc': 'डिजिटल इंडिया पहल और ई-गवर्नेंस मानकों के साथ संरेखित',
    'compliance.digital.india.std1': 'डिजिटल इंडिया',
    'compliance.digital.india.std2': 'ई-गवर्नेंस',
    'compliance.digital.india.std3': 'API मानक',
    'compliance.cyber.security': 'साइबर सुरक्षा',
    'compliance.cyber.security.desc': 'नियमित पेनिट्रेशन टेस्टिंग, वल्नरेबिलिटी असेसमेंट और सुरक्षा निगरानी',
    'compliance.cyber.security.std1': 'CERT-In दिशानिर्देश',
    'compliance.cyber.security.std2': 'साइबर सुरक्षा फ्रेमवर्क',
    'compliance.cyber.security.std3': '24/7 निगरानी',
    'compliance.certification.title': 'प्रमाणन और अनुपालन स्थिति',
    'compliance.cert.security.audit': 'सुरक्षा ऑडिट',
    'compliance.cert.security.audit.status': '✓ उत्तीर्ण',
    'compliance.cert.accessibility.test': 'एक्सेसिबिलिटी टेस्ट',
    'compliance.cert.accessibility.test.status': '✓ AA अनुपालक',
    'compliance.cert.data.protection': 'डेटा सुरक्षा',
    'compliance.cert.data.protection.status': '✓ प्रमाणित',
    'compliance.cert.performance': 'प्रदर्शन',
    'compliance.cert.performance.status': '✓ अनुकूलित',
    'forgot.password.title': 'पासवर्ड रीसेट करें',
    'forgot.password.description': 'OTP प्राप्त करने के लिए अपना ईमेल दर्ज करें',
    'forgot.password.email.label': 'ईमेल पता',
    'forgot.password.email.placeholder': 'engineer@vmc.gov.in',
    'forgot.password.send.otp': 'OTP भेजें',
    'forgot.password.sending': 'भेजा जा रहा है...',
    'forgot.password.back.to.login': 'लॉगिन पर वापस जाएं',
    'forgot.password.otp.title': 'OTP दर्ज करें',
    'forgot.password.otp.description': 'अपने ईमेल पर भेजा गया OTP दर्ज करें',
    'forgot.password.otp.sent': 'हमने 6 अंकों का कोड भेजा है',
    'forgot.password.verify.otp': 'OTP सत्यापित करें',
    'forgot.password.verifying': 'सत्यापित किया जा रहा है...',
    'forgot.password.resend.otp': 'OTP फिर से भेजें',
    'forgot.password.change.email': 'ईमेल बदलें',
    'forgot.password.new.password': 'नया पासवर्ड',
    'forgot.password.new.password.description': 'एक नया सुरक्षित पासवर्ड बनाएं',
    'forgot.password.new.password.placeholder': 'नया पासवर्ड दर्ज करें',
    'forgot.password.confirm.password': 'पासवर्ड की पुष्टि करें',
    'forgot.password.confirm.password.placeholder': 'नया पासवर्ड फिर से दर्ज करें',
    'forgot.password.show.password': 'पासवर्ड दिखाएं',
    'forgot.password.requirements': 'पासवर्ड में होना चाहिए:',
    'forgot.password.requirement.length': 'कम से कम 8 अक्षर',
    'forgot.password.requirement.mix': 'अक्षरों और संख्याओं का मिश्रण',
    'forgot.password.reset.button': 'पासवर्ड रीसेट करें',
    'forgot.password.resetting': 'रीसेट किया जा रहा है...',
    'forgot.password.success': 'पासवर्ड रीसेट सफल!',
    'forgot.password.success.description': 'आपका पासवर्ड सफलतापूर्वक रीसेट हो गया है',
    'forgot.password.success.message': 'आपका पासवर्ड सफलतापूर्वक रीसेट हो गया है। अब आप अपने नए पासवर्ड से लॉगिन कर सकते हैं।',
    'forgot.password.go.to.login': 'लॉगिन पर जाएं',
    'forgot.password.step.email': 'ईमेल',
    'forgot.password.step.otp': 'OTP',
    'forgot.password.step.password': 'पासवर्ड',
    'forgot.password.error.invalid.email': 'कृपया एक वैध ईमेल पता दर्ज करें',
    'forgot.password.error.invalid.otp': 'कृपया एक वैध 6-अंकीय OTP दर्ज करें',
    'forgot.password.error.password.mismatch': 'पासवर्ड मेल नहीं खाते',
    'forgot.password.error.password.weak': 'पासवर्ड कम से कम 8 अक्षरों का होना चाहिए'
  },
  
  gu: {
    'app.title': 'વીએમસી સિવિસેન્સ',
    'login': 'લોગિન',
    'back': 'પાછળ',
    'next': 'આગળ',
    'save': 'સેવ',
    'send': 'મોકલો',
    'draft': 'ડ્રાફ્ટ',
    'home.title': 'વડોદરા મહાનગરપાલિકા',
    'home.subtitle': 'સિવિસેન્સ - સ્માર્ટ સિવિક મોનિટરિંગ',
    'home.login': 'સિસ્ટમમાં લોગિન કરો',
    'feature.geofencing': 'જીઓ-ફેન્સિંગ',
    'feature.geofencing.desc': 'GPS થી આપોઆપ વોર્ડની ઓળખ',
    'feature.tracking': 'સમસ્યા ટ્રેકિંગ',
    'feature.tracking.desc': 'ખાડા, કચરો, ગટર અને અન્ય',
    'feature.dashboard': 'રોલ-બેસ્ડ ડેશબોર્ડ',
    'feature.dashboard.desc': 'ફીલ્ડ સ્ટાફથી કમિશનર સુધી',
    'feature.mobile': 'મોબાઇલ-ફર્સ્ટ PWA',
    'feature.mobile.desc': 'સરળ ઉપયોગ, મોટા બટન',
    'feature.offline': 'ઓફલાઇન-ફર્સ્ટ',
    'feature.offline.desc': 'નેટવર્ક વિના પણ કામ કરે છે',
    'feature.ai': 'AI સહાય',
    'feature.ai.desc': 'સ્માર્ટ સમસ્યા ઓળખ',
    'login.title': 'સિસ્ટમમાં લોગિન કરો',
    'login.select.role': 'ચાલુ રાખવા માટે તમારી ભૂમિકા પસંદ કરો',
    'login.signin.as': 'તરીકે સાઇન ઇન કરો',
    'login.username': 'યુઝરનેમ અથવા કર્મચારી આઇડી',
    'login.password': 'પાસવર્ડ',
    'login.remember': 'મને યાદ રાખો',
    'login.forgot': 'પાસવર્ડ ભૂલી ગયા?',
    'login.signin': 'સાઇન ઇન',
    'login.change.role': 'ભૂમિકા બદલો',
    'role.field.worker': 'ફીલ્ડ વર્કર',
    'role.field.worker.desc': 'જમીની સમસ્યાઓની રિપોર્ટ અને કેપ્ચર',
    'role.ward.engineer': 'વોર્ડ એન્જિનિયર',
    'role.ward.engineer.desc': 'વોર્ડ પ્રવૃત્તિઓનું નિરીક્ષણ અને ચકાસણી',
    'role.zone.officer': 'ઝોન અધિકારી',
    'role.zone.officer.desc': 'બહુ-વોર્ડ સંચાલનની દેખરેખ',
    'role.admin': 'એડમિન',
    'role.admin.desc': 'સિસ્ટમ-વ્યાપી વ્યવસ્થાપન',
    'dashboard.field.worker': 'ફીલ્ડ વર્કર',
    'dashboard.mobile.reporting': 'મોબાઇલ રિપોર્ટિંગ',
    'dashboard.online': 'ઓનલાઇન',
    'dashboard.offline': 'ઓફલાઇન',
    'dashboard.saved': 'સેવ્ડ',
    'dashboard.today': 'આજે',
    'dashboard.resolved': 'હલ',
    'dashboard.report.issue': 'સમસ્યા રિપોર્ટ કરો',
    'dashboard.quick.photo': 'ઝડપી ફોટો',
    'dashboard.my.location': 'મારું સ્થાન',
    'dashboard.saved.issues': 'સેવ્ડ ઇશ્યૂઝ',
    'dashboard.sync.now': 'સિંક કરો',
    'dashboard.all.synced': 'બધું સિંક થઈ ગયું',
    'dashboard.will.sync': 'ઓફલાઇન - ઓનલાઇન થવા પર સિંક થશે',
    'issue.report.title': 'સમસ્યા રિપોર્ટ કરો',
    'issue.select.type': 'સમસ્યાનો પ્રકાર પસંદ કરો',
    'issue.location.photos': 'સ્થાન અને ફોટો',
    'issue.description.submit': 'વર્ણન અને સબમિટ',
    'issue.get.location': 'સ્થાન મેળવો',
    'issue.getting.location': 'સ્થાન મેળવી રહ્યા છીએ...',
    'issue.location.captured': 'સ્થાન મળી ગયું ✓',
    'issue.take.photo': 'ફોટો લો',
    'issue.description.optional': 'સમસ્યાનું વર્ણન (વૈકલ્પિક)',
    'issue.ai.suggestion': 'AI સૂચન',
    'issue.priority': 'પ્રાથમિકતા',
    'issue.estimated.time': 'અનુમાનિત સમય',
    'issue.location': 'સ્થાન',
    'issue.photos': 'ફોટો',
    'issue.ward': 'વોર્ડ',
    'issue.saved.draft': 'મુદ્દો ડ્રાફ્ટમાં સેવ થઈ ગયો.',
    'issue.reported.success': 'મુદ્દો રિપોર્ટ થઈ ગયો!',
    'issue.fill.required': 'કૃપા કરીને બધી જરૂરી માહિતી ભરો.',
    'issue.save.error': 'સેવ કરવામાં ભૂલ.',
    'issue.location.error': 'સ્થાન મેળવી શકાયું નથી. કૃપા કરીને GPS ચાલુ કરો.',
    'issue.type.pothole': 'ખાડો',
    'issue.type.garbage': 'કચરો',
    'issue.type.drainage': 'ગટર',
    'issue.type.streetlight': 'સ્ટ્રીટ લાઇટ',
    'issue.type.road': 'રસ્તો',
    'issue.type.water': 'પાણી',
    'issue.type.manhole': 'ખુલ્લું મેનહોલ',
    'issue.type.cattle': 'આવારા પશુઓ',
    'network.no.connection': 'ઇન્ટરનેટ કનેક્શન નથી.',
    'network.syncing': 'સિંક થઈ રહ્યું છે...',
    'network.sync.complete': 'બધો ડેટા સિંક થઈ ગયો!',
    'network.sync.error': 'સિંકમાં ભૂલ.',
    'photo.captured': 'ફોટો કેપ્ચર થઈ ગયો! પછીથી રિપોર્ટ કરો.',
    'photo.location.not.available': 'સ્થાન ઉપલબ્ધ નથી',
    'home.description': 'ફીલ્ડ સ્ટાફ માટે AI-આધારિત જીઓ-ફેન્સ્ડ સિવિક ઇશ્યૂ મોનિટરિંગ સિસ્ટમ',
    'home.use.cases.title': 'મુખ્ય ઉપયોગ કિસ્સાઓ',
    'home.use.case.pothole': 'ચોમાસાની તપાસ પછી ખાડાઓ શોધો',
    'home.use.case.garbage': 'કચરા એકઠા થવાના હોટસ્પોટની ઓળખ કરો',
    'home.use.case.cattle': 'રસ્તા પર આવારા પશુઓની રિપોર્ટ કરો',
    'home.use.case.manhole': 'ખુલ્લા મેનહોલ અથવા ક્ષતિગ્રસ્ત રસ્તાઓને ફ્લેગ કરો',
    'home.use.case.resolution': 'વોર્ડ-વાઇઝ સમસ્યા નિરાકરણને ઝડપી બનાવો',
    'home.use.case.accountability': 'નિરાકરણ પુરાવા સાથે જવાબદારીમાં સુધારો કરો',
    'login.role.description': 'ફીલ્ડ વર્કર, વોર્ડ એન્જિનિયર, ઝોન અધિકારી અથવા એડમિન',
    'about.vadodara.title': 'આપણા વડોદરા વિશે',
    'about.vadodara.subtitle': 'સંસ્કારી નગરી',
    'about.vadodara.para1': 'વડોદરા, જે બરોડા તરીકે પણ જાણીતું છે, તે ગુજરાતના સૌથી વાઇબ્રન્ટ શહેરોમાંનું એક છે — સમૃદ્ધ વારસો, સાંસ્કૃતિક વિવિધતા અને ઝડપી શહેરી વિકાસનું મિશ્રણ. વિશ્વામિત્રી નદીના કિનારે આવેલું, તે તેના ભવ્ય મહેલો, કલા સંગ્રહાલયો અને શૈક્ષણિક સંસ્થાઓ માટે પ્રખ્યાત છે. એક સમયે ગાયકવાડ રાજવંશની બેઠક, વડોદરા આજે પણ તેના આર્કિટેક્ચર અને પરંપરાઓ દ્વારા શાહી આકર્ષણને પ્રતિબિંબિત કરે છે.',
    'about.vadodara.para2': 'આજે, વડોદરા ડિજિટલ શાસન, ઈન્ફ્રાસ્ટ્રક્ચર આધુનિકીકરણ અને ટકાઉ વૃદ્ધિને અપનાવતા ઝડપથી વિકસતા સ્માર્ટ શહેર તરીકે ઊભું છે. પેટ્રોકેમિકલ્સ, એન્જિનિયરિંગ અને આઈટીમાં મજબૂત ઔદ્યોગિક આધાર સાથે, આ શહેર નવીનતા અને નાગરિક પ્રગતિના કેન્દ્ર તરીકે પણ ખીલે છે. વડોદરા માત્ર એક શહેર નથી — તે એક પ્રગતિશીલ સમુદાય છે જ્યાં સંસ્કૃતિ ટેકનોલોજીને મળે છે.',
    'city.highlights.title': 'શહેરની મુખ્ય વિશેષતાઓ',
    'city.highlight.smart.city': 'સ્માર્ટ સિટી પહેલ',
    'city.highlight.smart.city.desc': 'વડોદરા સ્માર્ટ સિટીઝ મિશનનો ભાગ છે, જે શહેરી જીવનને વધારવા માટે ડિજિટલ ઈન્ફ્રાસ્ટ્રક્ચર, બુદ્ધિશાળી ટ્રાફિક સિસ્ટમ્સ અને ઈ-ગવર્નન્સ સેવાઓનો અમલ કરી રહ્યું છે.',
    'city.highlight.cultural': 'સાંસ્કૃતિક વારસો',
    'city.highlight.cultural.desc': 'લક્ષ્મી વિલાસ પેલેસ અને સયાજી ગાર્ડન જેવા સ્થળોનું ઘર, વડોદરા તેના શાહી વારસા અને નવરાત્રી જેવા જીવંત ઉત્સવોને ભવ્યતા સાથે ઉજવે છે.',
    'city.highlight.citizen': 'નાગરિક સેવાઓ',
    'city.highlight.citizen.desc': 'ઓનલાઈન બિલ પેમેન્ટથી લઈને ફરિયાદ નિવારણ સુધી, VMC તેના ડિજિટલ પ્લેટફોર્મ્સ દ્વારા આવશ્યક મ્યુનિસિપલ સેવાઓની સરળ ઍક્સેસ પ્રદાન કરે છે.',
    'city.highlight.sustainable': 'ટકાઉ વિકાસ',
    'city.highlight.sustainable.desc': 'લીલી જગ્યાઓ, પાણી વ્યવસ્થાપન અને સ્વચ્છ ઊર્જા પ્રોજેક્ટ્સ પર કેન્દ્રિત, વડોદરા પર્યાવરણ-અનુકૂળ શહેરી ભવિષ્ય તરફ સક્રિયપણે કામ કરી રહ્યું છે.',
    'city.highlight.industrial': 'ઔદ્યોગિક અને શૈક્ષણિક કેન્દ્ર',
    'city.highlight.industrial.desc': 'મહારાજા સયાજીરાવ યુનિવર્સિટી જેવી મુખ્ય ઔદ્યોગિક અને પ્રતિષ્ઠિત સંસ્થાઓ સાથે, વડોદરા આર્થિક અને શૈક્ષણિક ઉત્કૃષ્ટતાનું કેન્દ્ર છે.',
    'header.tagline': 'વડોદરા મહાનગરપાલિકા',
    'header.accessibility': 'ઍક્સેસિબિલિટી વિકલ્પો',
    'header.nav.field.worker': 'ફીલ્ડ વર્કર ડેશબોર્ડ',
    'header.nav.ward.engineer': 'વોર્ડ એન્જિનિયર ડેશબોર્ડ',
    'header.nav.zone.officer': 'ઝોન અધિકારી ડેશબોર્ડ',
    'header.nav.admin': 'એડમિન ડેશબોર્ડ',
    'footer.description.line1': 'વડોદરા મહાનગરપાલિકા માટે AI-આધારિત જીઓ-ફેન્સ્ડ સિવિક ઇશ્યૂ મોનિટરિંગ સિસ્ટમ',
    'footer.description.line2': 'ઓફલાઇન-ફર્સ્ટ ટેકનોલોજી સાથે ફીલ્ડ સ્ટાફને સશક્ત બનાવવું',
    'footer.contact.title': 'VMC નો સંપર્ક કરો',
    'footer.quick.links.title': 'ઝડપી લિંક્સ',
    'footer.portal.field.worker': 'ફીલ્ડ વર્કર પોર્ટલ',
    'footer.portal.ward.engineer': 'વોર્ડ એન્જિનિયર પોર્ટલ',
    'footer.portal.zone.officer': 'ઝોન અધિકારી પોર્ટલ',
    'footer.portal.admin': 'એડમિન પોર્ટલ',
    'footer.copyright': '© 2026 વડોદરા મહાનગરપાલિકા. બધા અધિકારો અનામત.',
    'footer.made.for': 'VMC ફીલ્ડ સ્ટાફ માટે બનાવેલ',
    'footer.offline.pwa': 'ઓફલાઇન-ફર્સ્ટ PWA',
    'footer.gps.enabled': 'GPS સક્ષમ',
    'compliance.title': 'સરકારી અનુપાલન',
    'compliance.description': 'VMC સિવિસેન્સ તમામ સરકારી ધોરણો અને નિયમોનું પાલન કરે છે',
    'compliance.data.security': 'ડેટા સુરક્ષા',
    'compliance.data.security.desc': 'એન્ડ-ટુ-એન્ડ એન્ક્રિપ્શન, સુરક્ષિત ડેટા સ્ટોરેજ અને નિયમિત સુરક્ષા ઑડિટ',
    'compliance.data.security.std1': 'ISO 27001',
    'compliance.data.security.std2': 'GDPR અનુપાલક',
    'compliance.data.security.std3': 'સરકારી ગ્રેડ સુરક્ષા',
    'compliance.accessibility': 'ઍક્સેસિબિલિટી',
    'compliance.accessibility.desc': 'સ્ક્રીન રીડર સપોર્ટ અને કીબોર્ડ નેવિગેશન સાથે WCAG 2.1 AA અનુપાલક',
    'compliance.accessibility.std1': 'WCAG 2.1 AA',
    'compliance.accessibility.std2': 'સેક્શન 508',
    'compliance.accessibility.std3': 'બહુભાષી સમર્થન',
    'compliance.transparency': 'પારદર્શિતા',
    'compliance.transparency.desc': 'ઓપન ડેટા નીતિઓ, ઑડિટ ટ્રેઇલ્સ અને જાહેર જવાબદારી પગલાં',
    'compliance.transparency.std1': 'RTI અનુપાલક',
    'compliance.transparency.std2': 'ઑડિટ ટ્રેઇલ્સ',
    'compliance.transparency.std3': 'જાહેર ડેટા ઍક્સેસ',
    'compliance.privacy': 'ગોપનીયતા સંરક્ષણ',
    'compliance.privacy.desc': 'સંમતિ વ્યવસ્થાપન અને ગોપનીયતા નિયંત્રણો સાથે નાગરિક ડેટા સંરક્ષણ',
    'compliance.privacy.std1': 'પ્રાઇવસી બાય ડિઝાઇન',
    'compliance.privacy.std2': 'સંમતિ વ્યવસ્થાપન',
    'compliance.privacy.std3': 'ડેટા ન્યૂનીકરણ',
    'compliance.digital.india': 'ડિજિટલ ઇન્ડિયા',
    'compliance.digital.india.desc': 'ડિજિટલ ઇન્ડિયા પહેલ અને ઈ-ગવર્નન્સ ધોરણો સાથે સંરેખિત',
    'compliance.digital.india.std1': 'ડિજિટલ ઇન્ડિયા',
    'compliance.digital.india.std2': 'ઈ-ગવર્નન્સ',
    'compliance.digital.india.std3': 'API ધોરણો',
    'compliance.cyber.security': 'સાયબર સુરક્ષા',
    'compliance.cyber.security.desc': 'નિયમિત પેનિટ્રેશન ટેસ્ટિંગ, વલ્નરેબિલિટી એસેસમેન્ટ અને સુરક્ષા નિરીક્ષણ',
    'compliance.cyber.security.std1': 'CERT-In માર્ગદર્શિકા',
    'compliance.cyber.security.std2': 'સાયબર સુરક્ષા ફ્રેમવર્ક',
    'compliance.cyber.security.std3': '24/7 નિરીક્ષણ',
    'compliance.certification.title': 'પ્રમાણપત્ર અને અનુપાલન સ્થિતિ',
    'compliance.cert.security.audit': 'સુરક્ષા ઑડિટ',
    'compliance.cert.security.audit.status': '✓ પાસ',
    'compliance.cert.accessibility.test': 'ઍક્સેસિબિલિટી ટેસ્ટ',
    'compliance.cert.accessibility.test.status': '✓ AA અનુપાલક',
    'compliance.cert.data.protection': 'ડેટા સંરક્ષણ',
    'compliance.cert.data.protection.status': '✓ પ્રમાણિત',
    'compliance.cert.performance': 'કાર્યક્ષમતા',
    'compliance.cert.performance.status': '✓ ઑપ્ટિમાઇઝ્ડ',
    'forgot.password.title': 'પાસવર્ડ રીસેટ કરો',
    'forgot.password.description': 'OTP મેળવવા માટે તમારું ઈમેલ દાખલ કરો',
    'forgot.password.email.label': 'ઈમેલ સરનામું',
    'forgot.password.email.placeholder': 'engineer@vmc.gov.in',
    'forgot.password.send.otp': 'OTP મોકલો',
    'forgot.password.sending': 'મોકલી રહ્યા છીએ...',
    'forgot.password.back.to.login': 'લોગિન પર પાછા જાઓ',
    'forgot.password.otp.title': 'OTP દાખલ કરો',
    'forgot.password.otp.description': 'તમારા ઈમેલ પર મોકલેલો OTP દાખલ કરો',
    'forgot.password.otp.sent': 'અમે 6-અંકનો કોડ મોકલ્યો છે',
    'forgot.password.verify.otp': 'OTP ચકાસો',
    'forgot.password.verifying': 'ચકાસી રહ્યા છીએ...',
    'forgot.password.resend.otp': 'OTP ફરી મોકલો',
    'forgot.password.change.email': 'ઈમેલ બદલો',
    'forgot.password.new.password': 'નવો પાસવર્ડ',
    'forgot.password.new.password.description': 'એક નવો સુરક્ષિત પાસવર્ડ બનાવો',
    'forgot.password.new.password.placeholder': 'નવો પાસવર્ડ દાખલ કરો',
    'forgot.password.confirm.password': 'પાસવર્ડની પુષ્ટિ કરો',
    'forgot.password.confirm.password.placeholder': 'નવો પાસવર્ડ ફરી દાખલ કરો',
    'forgot.password.show.password': 'પાસવર્ડ બતાવો',
    'forgot.password.requirements': 'પાસવર્ડમાં હોવું જોઈએ:',
    'forgot.password.requirement.length': 'ઓછામાં ઓછા 8 અક્ષરો',
    'forgot.password.requirement.mix': 'અક્ષરો અને સંખ્યાઓનું મિશ્રણ',
    'forgot.password.reset.button': 'પાસવર્ડ રીસેટ કરો',
    'forgot.password.resetting': 'રીસેટ કરી રહ્યા છીએ...',
    'forgot.password.success': 'પાસવર્ડ રીસેટ સફળ!',
    'forgot.password.success.description': 'તમારો પાસવર્ડ સફળતાપૂર્વક રીસેટ થઈ ગયો છે',
    'forgot.password.success.message': 'તમારો પાસવર્ડ સફળતાપૂર્વક રીસેટ થઈ ગયો છે. હવે તમે તમારા નવા પાસવર્ડથી લોગિન કરી શકો છો.',
    'forgot.password.go.to.login': 'લોગિન પર જાઓ',
    'forgot.password.step.email': 'ઈમેલ',
    'forgot.password.step.otp': 'OTP',
    'forgot.password.step.password': 'પાસવર્ડ',
    'forgot.password.error.invalid.email': 'કૃપા કરીને માન્ય ઈમેલ સરનામું દાખલ કરો',
    'forgot.password.error.invalid.otp': 'કૃપા કરીને માન્ય 6-અંકનો OTP દાખલ કરો',
    'forgot.password.error.password.mismatch': 'પાસવર્ડ મેળ ખાતા નથી',
    'forgot.password.error.password.weak': 'પાસવર્ડ ઓછામાં ઓછા 8 અક્ષરોનો હોવો જોઈએ'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    const savedLang = localStorage.getItem('vmc-language') as Language;
    if (savedLang && ['en', 'hi', 'gu'].includes(savedLang)) {
      setLanguage(savedLang);
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('vmc-language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  const getLanguageCode = (): string => {
    return LANGUAGE_CODES[language];
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t, getLanguageCode }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}